[View in Colaboratory](https://colab.research.google.com/github/Jeet0204/Receipt_Data_to_Database_Using_OCR_ML/blob/master/Model.ipynb)

**Downloading the tensorflow library and module of nltk library**

In [182]:
!pip install tflearn
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /content/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

**Importing the created json file**

In [1]:
from google.colab import files
files.upload()

Saving data.json to data (9).json


{'data.json': b'{\n\t"Company_name_Amazon": ["Amazon"],\n\t"Company_name_Iconflux" :["Iconflux"],\n\t"Company_name_Flipkart" :["Flipkart"],\n\t"Company_name_Apple": ["Apple"],\n\t"Company_name_Infosys": ["Infosys"],\n\t"Company_name_TCS": ["TCS"],\n\t"Company_name_Wipro": ["Wipro"],\n\t"Company_name_Google": ["Google"],\n\t"Company_name_Yahoo": ["Yahoo"],\n\t"Company_name_MIndtree": ["Mindtree"]\n\t\n}\n'}

**Importing all the necessary libraries**


In [0]:
import nltk
import numpy as np
import tflearn
import tensorflow as tf
import random
import json
import string
import unicodedata
import sys



**Loading the data and Pre-processing**

In [3]:
#This holds different punctuations in table format
tbl = dict.fromkeys(i for i in range(sys.maxunicode)
                    if unicodedata.category(chr(i)).startswith('P'))


#This method removes punctuation present in text
def remove_punctuation(text):
    return text.translate(tbl)

# variable to hold the Json data read from the file
data = None

# read the json file and load the training data
with open("data (9).json") as json_data:
    data = json.load(json_data)
    print(data)

#list of all categories to train
categories = list(data.keys())
# print(categories)

words = []
# print(words)

# a list of tuples with words in the sentence and category name
docs = []

for each_category in data.keys():
    for each_sentence in data[each_category]:
        each_sentence = remove_punctuation(each_sentence)
#         print(each_sentence)
        # extract words from each sentence and append to the word list
        w = nltk.word_tokenize(each_sentence)
        words.extend(w)
        docs.append((w, each_category))

print(words)
print(docs)


{'Company_name_Amazon': ['Amazon'], 'Company_name_Iconflux': ['Iconflux'], 'Company_name_Flipkart': ['Flipkart'], 'Company_name_Apple': ['Apple'], 'Company_name_Infosys': ['Infosys'], 'Company_name_TCS': ['TCS'], 'Company_name_Wipro': ['Wipro'], 'Company_name_Google': ['Google'], 'Company_name_Yahoo': ['Yahoo'], 'Company_name_MIndtree': ['Mindtree']}
['Amazon', 'Iconflux', 'Flipkart', 'Apple', 'Infosys', 'TCS', 'Wipro', 'Google', 'Yahoo', 'Mindtree']
[(['Amazon'], 'Company_name_Amazon'), (['Iconflux'], 'Company_name_Iconflux'), (['Flipkart'], 'Company_name_Flipkart'), (['Apple'], 'Company_name_Apple'), (['Infosys'], 'Company_name_Infosys'), (['TCS'], 'Company_name_TCS'), (['Wipro'], 'Company_name_Wipro'), (['Google'], 'Company_name_Google'), (['Yahoo'], 'Company_name_Yahoo'), (['Mindtree'], 'Company_name_MIndtree')]


**Modelling the data according to the tensorflow specification**

In [9]:
# create our training data
training = []
output = []
# create an empty array for our output
output_empty = [0] * len(categories)
print(output_empty)
 
for doc in docs:
    # initialize our bag of words for each document in the list
    bow = []
    # list of tokenized words for the pattern
    token_words = doc[0]
#     print(token_words)

    for w in words:
        bow.append(1) if w in token_words else bow.append(0)
#         print(bow)
#     print(bow) 

    output_row = list(output_empty)
    output_row[categories.index(doc[1])] = 1
    print(output_row)
    # our training set will contain a the bag of words model and the output row that tells which catefory that bow belongs to.
    training.append([bow, output_row])
 
    # shuffle our features 
random.shuffle(training)
training = np.array(training)
print(training) 

# trainX contains the Bag of words and train_y contains the label/ category
train_x = list(training[:,0])
train_y = list(training[:,1])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[[[0 1 0 0 0 0 0 0 0 0]
  [0 1 0 0 0 0 0 0 0 0]]

 [[0 0 0 1 0 0 0 0 0 0]
  [0 0 0 1 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 1 0]
  [0 0 0 0 0 0 0 0 1 0]]

 [[0 0 0 0 0 0 1 0 0 0]
  [0 0 0 0 0 0 1 0 0 0]]

 [[1 0 0 0 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 1 0 0 0 0]
  [0 0 0 0 0 1 0 0 0 0]]

 [[0 0 1 0 0 0 0 0 0 0]
  [0 0 1 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 1 0 0]
  [0 0 0 0 0 0 0 1 0 0]]

 [[0 0 0 0 0 0 0 0 0 1]
  [0 0 0 0 0 0 0 0 0 1]]

 [[0 0 0 0 1 0 0 0 0 0]
  [0 0 0 0 1 0 0 0 0 0]]]


**Modelling the deep  neural network using tensorflow**

In [11]:
tf.reset_default_graph()

# Building neural network
net = tflearn.input_data(shape=[None, len(train_x[0])])
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, len(train_y[0]), activation='softmax')
net = tflearn.regression(net)

# Defining the model
model = tflearn.DNN(net, tensorboard_dir='tflearn_logs')

# Start training (Gradient Descent)
model.fit(train_x, train_y, n_epoch=500, batch_size=8, show_metric=True)
model.save('model.tflearn')






Training Step: 999  | total loss: 0.59413 | time: 0.003s
| Adam | epoch: 500 | loss: 0.59413 - acc: 0.8632 -- iter: 08/10
Training Step: 1000  | total loss: 0.59925 | time: 0.006s
| Adam | epoch: 500 | loss: 0.59925 - acc: 0.8769 -- iter: 10/10
--
INFO:tensorflow:/content/model.tflearn is not in all_model_checkpoint_paths. Manually adding it.
['Lines', 'HasOverlay', 'False', 'Message', 'Text', 'overlay', 'is', 'not', 'provided', 'as', 'it', 'is', 'not', 'requested', '1', 'Infosys', 'Bill', 'To', 'Jeet', 'Jlvrajani', 'DESCRIPTION', 'Terms', 'Conditions', 'Payment', 'is', 'due', 'within', '15', 'days', 'Receipt', 'Receipt', 'Date', 'RECEIPT', '100', '03062018', 'TOTAL', 'AMOUNT', '200000', '200000']
Company_name_Infosys
['Lines', 'HasOverlay', 'False', 'Message', 'Text', 'overlay', 'is', 'not', 'provided', 'as', 'it', 'is', 'not', 'requested', '1', 'Wipro', 'Bill', 'To', 'Jeet', 'Jlvrajani', 'DESCRIPTION', 'Terms', 'Conditions', 'Payment', 'is', 'due', 'within', '15', 'days', 'Receipt', 

**Prediction based on the trained model**

In [0]:
sent_1 = "[{'Lines': [], 'HasOverlay': False, 'Message': 'Text overlay is not provided as it is not requested'}, 1, 'Infosys \r\nBill To \r\nJeet Jlvrajani \r\nDESCRIPTION \r\nTerms & Conditions \r\nPayment is due within 15 days \r\nReceipt # \r\nReceipt Date \r\nRECEIPT \r\n100 \r\n03/06/2018 \r\nTOTAL \r\nAMOUNT \r\n2,000.00 \r\n2,000.00 \r\n', '', '']  "
sent_2 = "[{'Lines': [], 'HasOverlay': False, 'Message': 'Text overlay is not provided as it is not requested'}, 1, 'Wipro \r\nBill To \r\nJeet Jlvrajani \r\nDESCRIPTION \r\nTerms & Conditions \r\nPayment is due within 15 days \r\nReceipt # \r\nReceipt Date \r\nRECEIPT \r\n100 \r\n03/06/2018 \r\nTOTAL \r\nAMOUNT \r\n2,000.00 \r\n2,000.00 \r\n', '', '']  "
sent_3 = " [{'Lines': [], 'HasOverlay': False, 'Message': 'Text overlay is not provided as it is not requested'}, 1, 'Iconflux \r\nBill To \r\nJeet Jlvrajani \r\nDESCRIPTION \r\nTerms & Conditions \r\nPayment is due within 15 days \r\nReceipt # \r\nReceipt Date \r\nRECEIPT \r\n100 \r\n03/06/2018 \r\nTOTAL \r\nAMOUNT \r\n2,000.00 \r\n2,000.00 \r\n', '', ''] "
sent_4 = "[{'Lines': [], 'HasOverlay': False, 'Message': 'Text overlay is not provided as it is not requested'}, 1, 'TCS \r\nBill To \r\nJeet Jlvrajani \r\nDESCRIPTION \r\nTerms & Conditions \r\nPayment is due within 15 days \r\nReceipt # \r\nReceipt Date \r\nRECEIPT \r\n100 \r\n03/06/2018 \r\nTOTAL \r\nAMOUNT \r\n2,000.00 \r\n2,000.00 \r\n', '', '']  "
sent_5 = " [{'Lines': [], 'HasOverlay': False, 'Message': 'Text overlay is not provided as it is not requested'}, 1, 'Google \r\nBill To \r\nJeet Jlvrajani \r\nDESCRIPTION \r\nTerms & Conditions \r\nPayment is due within 15 days \r\nReceipt # \r\nReceipt Date \r\nRECEIPT \r\n100 \r\n03/06/2018 \r\nTOTAL \r\nAMOUNT \r\n2,000.00 \r\n2,000.00 \r\n', '', ''] "




each_sent_1 = remove_punctuation(sent_1)
each_sent_2 = remove_punctuation(sent_2)
each_sent_3 = remove_punctuation(sent_3)
each_sent_4 = remove_punctuation(sent_4)
each_sent_5 = remove_punctuation(sent_5)

# a method that takes in a sentence and list of all words
# and returns the data in a form the can be fed to tensorflow

def get_tf_record(sentence):
    global words
    # tokenize the pattern
    sentence_words = nltk.word_tokenize(sentence)
    print(sentence_words)
  
    # bag of words
    bow = [0]*len(words)
    for s in sentence_words:
        for i, w in enumerate(words):
            if w == s:
                bow[i] = 1

    return(np.array(bow))


#Prection of 5 sentences
print(categories[np.argmax(model.predict([get_tf_record(each_sent_1)]))])
print(categories[np.argmax(model.predict([get_tf_record(each_sent_2)]))])
print(categories[np.argmax(model.predict([get_tf_record(each_sent_3)]))])
print(categories[np.argmax(model.predict([get_tf_record(each_sent_4)]))])
print(categories[np.argmax(model.predict([get_tf_record(each_sent_5)]))])

